

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aimeos_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./myshop:/var/www
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"   # expose Laravel app to host
    command: php artisan serve --host=0.0.0.0 --port=8000


  web:
    image: nginx:alpine
    container_name: aimeos_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./myshop:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8
    container_name: aimeos_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: aimeos
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: aimeos
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: aimeos_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: aimeos_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"


  frontend:
    image: node:20
    container_name: aimeos_frontend
    working_dir: /usr/src/app
    volumes:
    - ./frontend:/usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
    - "3000:3000"
    environment:
    - NEXT_PUBLIC_API_URL=http://localhost:8000/jsonapi
    depends_on:
    - app
     

volumes:
  db_data:
